# Generated by Django 2.0.6 on 2018-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Required',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=39)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('city', models.CharField(max_length=22)),
                ('responsiblity', models.TextField(default=True, max_length=200)),
                ('be_cgpa', models.IntegerField()),
                ('hsc_percent', models.IntegerField()),
                ('ssc_percent', models.IntegerField()),
                ('skilling', models.CharField(max_length=30)),
            ],
        ),
    ]
